name: ScanNgo-api-build-deploy-pipeline

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create config.yaml
      run: |
        touch config.yaml
        echo "database:" >> config.yaml
        echo "  db_port: ${{ secrets.DB_PORT }}" >> config.yaml
        echo "  db_name: ${{ secrets.DB_NAME }}" >> config.yaml
        echo "  db_host: ${{ secrets.DB_HOST }}" >> config.yaml
        echo "  db_user: ${{ secrets.DB_USER }}" >> config.yaml
        echo "  db_passowrd: ${{ secrets.DB_PASWORD }}" >> config.yaml
        
#     - name: AWS ECR - Build Docker and Push to ECR
#       # You may pin to the exact commit or the version.
#       # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
#       uses: kciter/aws-ecr-action@v4
#       with:
#         # The AWS access key id
#         access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         # The AWS secret access key
#         secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         # AWS Account ID
#         account_id: ${{ secrets.AWS_ACCOUNT_ID }}
#         # Name of your ECR repository
#         repo: ${{ secrets.ECR_REPO_NAME }}
#         # The AWS region
#         region: us-west-2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: ECR push and ECS deploy
      uses: jaroldwong/ecr-push-and-ecs-deploy@v1
      with:
        ecr-registry: ${{ steps.login-ecr.outputs.registry }}
        ecr-repository:  ${{ secrets.ECR_REPO_NAME }}
        ecs-cluster: scanngo-cluster
        ecs-service: scanngo-service
