name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create config.yaml
      run: |
        touch config.yaml
        echo "database:" >> config.yaml
        echo "  db_port: ${{ secrets.PORT }}" >> config.yaml
        echo "  db_name: ${{ secrets.DB_NAME }}" >> config.yaml
        echo "  db_host: ${{ secrets.DB_HOST }}" >> config.yaml
        echo "  db_user: ${{ secrets.DB_USER }}" >> config.yaml
        echo "  db_passowrd: ${{ secrets.DB_PASWORD }}" >> config.yaml
        
    - name: AWS ECR - Build Docker and Push to ECR
      # You may pin to the exact commit or the version.
      # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
      uses: kciter/aws-ecr-action@v4
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Account ID
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        # Name of your ECR repository
        repo: ${{ secrets.REPO_NAME }}
        # The AWS region
        region: us-east-1
